// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { sidebar } from './sidebar.mjs';

// https://astro.build/config
export default defineConfig({
	// Canonical site URL — used for canonical links and the sitemap.
	site: 'https://doc.anytype.io',
	integrations: [
		starlight({
			title: 'Anytype Docs',
			description:
				'Official documentation for Anytype — the local-first, end-to-end encrypted, no-lock-in everything app.',
			logo: {
				src: './src/assets/logo-square.png',
				alt: 'Anytype',
				// Show the "Anytype Docs" wordmark next to the app icon (GitBook-style).
				replacesTitle: false,
			},
			favicon: '/favicon.png',
			// English is the root locale; Starlight falls back to English for
			// pages a locale hasn't translated yet.
			defaultLocale: 'root',
			locales: {
				root: { label: 'English', lang: 'en' },
				es: { label: 'Español', lang: 'es' },
				fr: { label: 'Français', lang: 'fr' },
			},
			editLink: {
				baseUrl: 'https://github.com/anyproto/docs/edit/main/',
			},
			// GitBook-style code blocks: rounded, hairline border, JetBrains Mono.
			expressiveCode: {
				themes: ['github-dark-default', 'github-light-default'],
				styleOverrides: {
					borderRadius: '0.5rem',
					borderColor: 'var(--sl-color-hairline-light)',
					codeFontFamily: "'JetBrains Mono Variable', ui-monospace, monospace",
				},
			},
			customCss: [
				// Self-hosted fonts (no external CDN — on-brand for a privacy product).
				'@fontsource-variable/inter',
				'@fontsource-variable/jetbrains-mono',
				'./src/styles/custom.css',
			],
			social: [
				{
					icon: 'discourse',
					label: 'Community Forum',
					href: 'https://community.anytype.io',
				},
				{
					icon: 'github',
					label: 'GitHub',
					href: 'https://github.com/anyproto',
				},
			],
			// Sidebar mirroring the original GitBook SUMMARY.md (generated by the
			// migration; edit sidebar.mjs to reorganize navigation).
			sidebar,
		}),
	],
});
